### CREATE five documents.
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "name": "Cat Hat",
    "time": 2,
    "rating": 5,
    "date": "12-02-23"
}


### CREATE 2
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "name": "Frog",
    "time": 3,
    "rating": 4,
    "date": "02-25-23"
}

### CREATE 3
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "name": "Granny Squares Bag",
    "time": 12,
    "rating": 4,
    "date": "03-13-23"
}

### CREATE 4
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "name": "Accordian Tank Top",
    "time": 17,
    "rating": 4,
    "date": "07-30-23"
}

### CREATE 5
POST http://localhost:3000/projects HTTP/1.1
content-type: application/json

{
    "name": "Backless Dress",
    "time": 6,
    "rating": 3,
    "date": "08-18-23"
}


### RETRIEVE all documents.
GET http://localhost:3000/projects HTTP/1.1



### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/projects/656cfe36eda9ebc327337824 HTTP/1.1


### UPDATE one document's time, by ID.
### Replace the ID in the following request with one that exists
### and update the time:
PUT http://localhost:3000/projects/656cfe36eda9ebc327337824 HTTP/1.1
content-type: application/json

{
    "name": "Cat Hat",
    "time": 2,
    "rating": 5,
    "date": "12-02-23"
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/projects/656cfe36eda9ebc327337824 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/projects HTTP/1.1

